### ISSUE TITLE
why can eosjs run in node and browser, yet cannot run in react native?

### ISSUE THREAD

**Issue by JadeTao** [Game-X-Coin/eosjs-rn#7]
I know eosjs(especially ecc module) need some node built-in modules.
but now that in some easy way it can run in web browser.
why can't we use its browser version in react native?
so my question is
1. what happened during eosjs node version's changing to browser version?
2. why browser version is not runnable in react native?
many thanks if you can tell me.

**Comment by JadeTao** [comment]
my guess: it is because we get the browser version by browserify. And the output of browserify cannot run in reactnative.
like: https://stackoverflow.com/questions/40777337/how-to-use-browserified-libraries-in-react-native

**Comment by ehnawh** [comment]
This is because the browserify provided by current eosjs version is incompatible with react native.
In order to operate in react native, other work is required like custom transformers
